apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voyageone.fullname" . }}
data:
{{- range $path, $_ :=  .Files.Glob  "conf/*.yaml" }}
{{ $.Files.Get $path | trimSuffix "\n" | indent 2 }}
{{- end -}}
